dataset_root: "./data/ScanNet++"

train_list: "./data/scannet++/train_list.txt"
val_list: "./data/scannet++/val_list.txt"

train_n_samples_per_subset: 4 # 340*6=2040
val_n_samples_per_subset: 1 # 测试集40个场景

sort_frames: True
train_random_frame_sample: True

image_height: 512
image_width: 512

min_interval: 1 # frame之间最小间隔
max_interval: 6 # frame之间最大间隔

train_masking_type: "random" # "random_object_mask" # "random"
train_masking_params: null

val_masking_type: "fixed"
val_masking_params: null